// <auto-generated />
using System;
using HackGame.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HackGame.Api.Migrations
{
    [DbContext(typeof(HackerGameDbContext))]
    [Migration("20231003082046_second")]
    partial class second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HackGame.Api.Models.Database", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<float>("ProcessorGhz")
                        .HasColumnType("float");

                    b.Property<Guid?>("UserIdFk")
                        .HasColumnType("char(36)");

                    b.Property<string>("indexDescription")
                        .HasColumnType("longtext");

                    b.Property<int>("internetKbs")
                        .HasColumnType("int");

                    b.Property<string>("ipAddress")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<int>("memory")
                        .HasColumnType("int");

                    b.Property<int>("money")
                        .HasColumnType("int");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("secret_Verifycation_Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("storageMb")
                        .HasColumnType("int");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("UserIdFk");

                    b.ToTable("Databases");
                });

            modelBuilder.Entity("HackGame.Api.Models.Software", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("DatabaseId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("isDeleteable")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isInstalled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("size")
                        .HasColumnType("int");

                    b.Property<float>("strength")
                        .HasColumnType("float");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("DatabaseId");

                    b.ToTable("Software_Data");
                });

            modelBuilder.Entity("HackGame.Api.Models.TimedTask", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("endTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("softwareId")
                        .HasColumnType("char(36)");

                    b.Property<string>("targetIp")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.Property<Guid>("userId")
                        .HasColumnType("char(36)");

                    b.HasKey("id");

                    b.HasIndex("softwareId");

                    b.HasIndex("userId");

                    b.ToTable("Timed_Tasks");
                });

            modelBuilder.Entity("HackGame.Api.Models.UserData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Login_Data");
                });

            modelBuilder.Entity("HackGame.Api.Models.UserInventoryData", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("MilitaryTechComps")
                        .HasColumnType("int");

                    b.Property<int>("highTechComps")
                        .HasColumnType("int");

                    b.Property<int>("microControllers")
                        .HasColumnType("int");

                    b.Property<int>("techComps")
                        .HasColumnType("int");

                    b.Property<Guid>("userId")
                        .HasColumnType("char(36)");

                    b.HasKey("id");

                    b.HasIndex("userId");

                    b.ToTable("Inventory_Data");
                });

            modelBuilder.Entity("HackGame.Api.Models.Database", b =>
                {
                    b.HasOne("HackGame.Api.Models.UserData", "User")
                        .WithMany()
                        .HasForeignKey("UserIdFk");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HackGame.Api.Models.Software", b =>
                {
                    b.HasOne("HackGame.Api.Models.Database", "data")
                        .WithMany()
                        .HasForeignKey("DatabaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("data");
                });

            modelBuilder.Entity("HackGame.Api.Models.TimedTask", b =>
                {
                    b.HasOne("HackGame.Api.Models.Software", "software")
                        .WithMany()
                        .HasForeignKey("softwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HackGame.Api.Models.UserData", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("software");

                    b.Navigation("user");
                });

            modelBuilder.Entity("HackGame.Api.Models.UserInventoryData", b =>
                {
                    b.HasOne("HackGame.Api.Models.UserData", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });
#pragma warning restore 612, 618
        }
    }
}
