// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlGzVWKBwWrbt4pqz4YjXAX8TzOmVXh1Q',
    appId: '1:1025295525427:web:ca85cabd98c2a70206a546',
    messagingSenderId: '1025295525427',
    projectId: 'h3database',
    authDomain: 'h3database.firebaseapp.com',
    storageBucket: 'h3database.appspot.com',
    measurementId: 'G-DZ759WE7BX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTO8sc4LLCckv9ZzjDWIAOdZDgTKiW_YA',
    appId: '1:1025295525427:android:f883878906c737b006a546',
    messagingSenderId: '1025295525427',
    projectId: 'h3database',
    storageBucket: 'h3database.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB86swFwHXdjSjjpnQU96fG3g2JjxiUAYY',
    appId: '1:1025295525427:ios:4622e5d70b4c015506a546',
    messagingSenderId: '1025295525427',
    projectId: 'h3database',
    storageBucket: 'h3database.appspot.com',
    iosBundleId: 'com.example.opslagsTavle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB86swFwHXdjSjjpnQU96fG3g2JjxiUAYY',
    appId: '1:1025295525427:ios:e08058d90ebbe34306a546',
    messagingSenderId: '1025295525427',
    projectId: 'h3database',
    storageBucket: 'h3database.appspot.com',
    iosBundleId: 'com.example.opslagsTavle.RunnerTests',
  );
}
